---
driver:
  name: lxd_cli
## docker.io need specificl profile else 'PermissionError: [Errno 13] Permission denied: '/sys/kernel/security/apparmor/profiles''
## https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/
#  profile: [ default, docker ]
## required to loop mount
  config:
    security.privileged: true
## create a template?
#  publish_image_name: "kitchen-ffate-#{instance.name}"
#  use_publish_image: true
#  publish_image_before_destroy: true
#  publish_image_overwrite: true

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  ansible_version: 2.6.2.0
  ansible_verbose: true
#  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
#  env_vars:
#    ANSIBLE_KEEP_REMOTE_FILES: 1
  require_pip: true
  ansible_version: 2.6.0

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:
  - name: default-ffate-testing
    run_list:
    attributes:

