---

- stat: path={{ jenkins_root }}/views/{{ view_name | basename }}
  register: viewdir

- stat: path={{ view_file }}
  register: viewf
- fail: msg="Missing view file for jenkins '{{ view_file }}'"
  when: not viewf.stat.exists

- name: load view example {{ view_name }} into jenkins through cli
  shell: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    create-view {{ view_name | basename }}
    --username {{ jenkins_admin_username }}
    --password {{ jenkins_admin_password }} < {{ view_file }}
  args:
    creates: "{{ jenkins_root }}/views/{{ view_name | basename }}"
  when: not viewdir.stat.exists

