---

- name: FATAL
  fail: msg="This role is only compatible with Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

## comment or review depending on your need
#- include_vars: main.yml

- include: ffate.yml

- include: testing.yml
  when: ffate_testing
