---

- name: restart nginx
  service: name=nginx state=restarted

- name: restart postgres
  service: name=postgresql state=restarted

- name: remove ffate db marker if present
  file: dest=/root/.ffate_import_db state=absent
